# Generated by Django 5.1.1 on 2024-09-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade_disponivel', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
