# Generated by Django 5.1.1 on 2024-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(default='Descrição não fornecida'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade_disponivel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
