# Generated by Django 5.1.1 on 2024-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_equipamento_quantidade_alter_equipamento_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='quantidade_disponivel',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
